environment                 = "dev"
cognito_user_pool_id        = "ca-central-1_fuT9Uqhn9"
cognito_identity_pool_name  = "arq-id-pool"
cognito_user_pool_client_id = "4j9v08ni345r1masnlh8bnoik"
cloudfront_alias            = "demo.nb.cll-ldc.ca"
acm_certificate_id          = "ded59597-65d7-4b09-bec9-6a80b4f554ad"
