export const languages = {
  en: {
    "main-title": "Create an inference job",
    "new-job": "New job",
    "claude-model-label": "Select claude AI language model",
    "claude-files-label": "Select one or more files",
    "source-code-input": {
      text: "Enter source code here",
      "data-val-required": "The 'Last Name' field is required.",
    },
    "source-code-label": "Source Code",
    "source-code-file-span":
      "Maximum size exceeded. Maximum size allowed is 10 MB.",
    "invalid-file-type": "The selected file type is not allowed.",
    "fields-required": "All fields marked with * are required ",
    "upload-label": "Upload Source Code File",
    "upload-button-span": "Upload File",
    "prompt-label": "Enter your request",
    "prompt-input": {
      text: "Enter your prompt here",
      "data-val-phone":
        "The 'Phone' field must be a valid telephone number (e.g., 418 111 1111).",
    },
    "response-label": "Response",
    "generate-button-span": "Generate",
    "download-file-button-span": "Download file",
    "delete-file-button-span": "Delete the selected files",
    "search-files": "Search files...",
    "add-files": "Add files",
    "error-message": "Select at least one file and provide an instruction.",
    close: "Cancel",
    submit: "Submit",
    submitting: "Submitting...",
    "download-button-span": "Download Response",
    "loading-span": "Loading...",
    "last-name-label": "Last Name",
    "last-name-input": {
      text: "Enter your last name",
      "data-val-required": "The 'Last Name' field is required.",
    },
    "file-name": "File Name",
    "file-last-update": "Last update: ",
    "list-of-jobs": "List of Jobs",
    "no-jobs-found": "No jobs found.",
    "search-jobs-placeholder": "Search by Job ID, Prompt, or Status",
    "loading-jobs": "Loading jobs...",
    "error-fetch-jobs": "Error fetching jobs",
    "error-loading-jobs": "Error while loading jobs.",
    "failed-to-fetch-link": "Failed to fetch link for file:",
    status: "Status: ",
    "created-at": "Created at: ",
    "link-not-available": "Link not available yet",
    "job-search-placeholder": "Search by prompt or status",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    "refresh-search": "Refresh search",
    "selected-files": "Selected files :",
    "allowed-format":
      "Only files in txt, .cs, .vb, .sql, .js, .ts, .tsx, .py, .java, .net, .c, .cpp, .rb, .go, .sh, .hs, .jar format are allowed",
    files: "Files: ",
    prompt: "Prompt: ",
    "request-success": "Your request has been successfully submitted",
    "log-out": "Log out",
  },
  fr: {
    "main-title": "Création d'une tache d'inférence",
    "new-job": "Nouveau processus",
    "claude-model-label": "Selectionner le modèle de langage claude AI",
    "claude-files-label": "Sélectionner un ou plusieurs fichiers",
    "source-code-input": {
      text: "Entrez le code source ici...",
      "data-val-required": "Le champ 'Nom' est requis.",
    },
    "source-code-label": "Code Source",
    "source-code-file-span":
      "Taille maximale dépassée. La taille maximale autorisée est de 10 Mo.",
    "invalid-file-type": "Le type de fichier sélectionné n'est pas autorisé.",
    "fields-required":
      "Tous les champs marqués d'un astérisque * sont obligatoires",
    "upload-label": "Ajouter des fichiers ",
    "upload-button-span": "Téléverser les fichiers",
    "prompt-label": "Saisir votre demande",
    "prompt-input": {
      text: "Entrez votre prompt ici",
      "data-val-phone":
        "Le champ 'Téléphone' doit être un numéro de téléphone valide (ex. : 418 111 1111).",
    },
    "file-list-label": "Liste des fichiers",
    "response-label": "Réponse",
    "generate-button-span": "Générer",
    "download-file-button-span": "Télécharger le fichier",
    "delete-file-button-span": "Supprimer les fichiers sélectionnés",
    "search-files": "Recherchez des fichiers",
    "add-files": "Ajouter des fichiers",
    "error-message":
      "Sélectionner au moins un fichier et fournir une instruction.",
    close: "Cancel",
    submit: "Soumettre",
    submitting: "Envoi en cours...",
    "download-button-span": "Télécharger la réponse",
    "loading-span": "Chargement...",
    "last-name-label": "Nom",
    "last-name-input": {
      text: "Entrez votre nom",
      "data-val-required": "Le champ 'Nom' est requis.",
    },
    "file-name": "Nom du fichier",
    "file-last-update": "Dernière mise à jour: ",
    "list-of-jobs": "Liste des processus",
    "no-jobs-found": "Aucun processus trouvé.",
    "search-jobs-placeholder":
      "Rechercher par ID de processus, prompt ou statut",
    "loading-jobs": "Chargement des processus...",
    "error-fetch-jobs": "Erreur lors de la récupération des processus",
    "error-loading-jobs": "Erreur lors du chargement des processus.",
    "failed-to-fetch-link":
      "Échec de la récupération du lien pour le fichier :",
    status: "Statut : ",
    "created-at": "Créé le : ",
    "link-not-available": "Lien non disponible pour le moment",
    "job-search-placeholder": "Rechercher par prompt ou par statut",
    previous: "Précédent",
    next: "Suivant",
    page: "Page",
    of: "sur",
    "refresh-search": "Reactualiser la recherche",
    "selected-files": "Fichiers sélectionnés :",
    "allowed-format": {
      "first-ligne": "Seul les fichiers au format txt, .cs, .vb, .sql, .cs, ",
      "second-ligne": ".vb,  .sql, .js, .ts, .tsx, .py, .java, .net, .c, ",
      "third-ligne": ".cpp, .rb, .go, .sh, .hs, .jar sont autorisés",
    },
    files: "Fichiers : ",
    prompt: "Prompt : ",
    "request-success": "Votre requête a bien été envoyée",
    "log-out": "Déconnexion",
  },
};
