export const languages = {
  en: {
    "main-title": "Generative AI",
    "claude-model-label": "Claude AI Language Model",
    "source-code-input": {
      text: "Enter source code here...",
      "data-val-required": "The 'Last Name' field is required.",
    },
    "source-code-label": "Source Code",
    "source-code-file-span":
      "Maximum size exceeded. Maximum size allowed is 10 MB.",
    "invalid-file-type": "The selected file type is not allowed.",
    "upload-label": "Upload Source Code File",
    "upload-button-span": "Upload Source Code File",
    "prompt-label": "Prompt",
    "prompt-input": {
      text: "Enter your prompt here...",
      "data-val-phone":
        "The 'Phone' field must be a valid telephone number (e.g., 418 111 1111).",
    },
    "response-label": "Response",
    "generate-button-span": "Generate",
    "download-file-button-span": "Download file",
    "delete-file-button-span": "Delete the selected files",
    "search-files": "Search files...",
    "add-files": "Add files",
    "error-message":
      "Please select at least one file and provide an instruction.",
    close: "Close",
    submit: "Submit",
    submitting: "Submitting...",
    "download-button-span": "Download Response",
    "loading-span": "Loading...",
    "last-name-label": "Last Name",
    "last-name-input": {
      text: "Enter your last name",
      "data-val-required": "The 'Last Name' field is required.",
    },
    "file-name": "File Name",
    "file-last-update": "Last update: ",
    "list-of-jobs": "List of Jobs",
    "no-jobs-found": "No jobs found.",
    "search-jobs-placeholder": "Search by Job ID, Prompt, or Status",
    "loading-jobs": "Loading jobs...",
    "error-fetch-jobs": "Error fetching jobs",
    "error-loading-jobs": "Error while loading jobs.",
    "failed-to-fetch-link": "Failed to fetch link for file:",
    status: "Status:",
    "created-at": "Created at: ",
    "link-not-available": "Link not available yet",
    "job-search-placeholder": "Search by prompt or status",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    "refresh-search": "Refresh search",
  },
  fr: {
    "main-title": "IA générative",
    "claude-model-label": "Modèle de Langage Claude AI",
    "source-code-input": {
      text: "Entrez le code source ici...",
      "data-val-required": "Le champ 'Nom' est requis.",
    },
    "source-code-label": "Code Source",
    "source-code-file-span":
      "Taille maximale dépassée. La taille maximale autorisée est de 10 Mo.",
    "invalid-file-type": "Le type de fichier sélectionné n'est pas autorisé.",
    "upload-label": "Télécharger le fichier de code source",
    "upload-button-span": "Télécharger le fichier de code source",
    "prompt-label": "Prompt",
    "prompt-input": {
      text: "Entrez votre prompt ici...",
      "data-val-phone":
        "Le champ 'Téléphone' doit être un numéro de téléphone valide (ex. : 418 111 1111).",
    },
    "file-list-label": "Liste des fichiers",
    "response-label": "Réponse",
    "generate-button-span": "Générer",
    "download-file-button-span": "Télécharger le fichier",
    "delete-file-button-span": "Supprimer les fichiers sélectionnés",
    "search-files": "Rechercher des fichiers...",
    "add-files": "Ajouter des fichiers",
    "error-message":
      "Veuillez sélectionner au moins un fichier et fournir une instruction.",
    close: "Fermer",
    submit: "Soumettre",
    submitting: "Envoi en cours...",
    "download-button-span": "Télécharger la réponse",
    "loading-span": "Chargement...",
    "last-name-label": "Nom",
    "last-name-input": {
      text: "Entrez votre nom",
      "data-val-required": "Le champ 'Nom' est requis.",
    },
    "file-name": "Nom du fichier",
    "file-last-update": "Dernière mise à jour: ",
    "list-of-jobs": "Liste des emplois",
    "no-jobs-found": "Aucun emploi trouvé.",
    "search-jobs-placeholder": "Rechercher par ID d'emploi, prompt ou statut",
    "loading-jobs": "Chargement des emplois...",
    "error-fetch-jobs": "Erreur lors de la récupération des emplois",
    "error-loading-jobs": "Erreur lors du chargement des emplois.",
    "failed-to-fetch-link":
      "Échec de la récupération du lien pour le fichier :",
    status: "Statut :",
    "created-at": "Créé le : ",
    "link-not-available": "Lien non disponible pour le moment",
    "job-search-placeholder": "Rechercher par prompt ou par statut",
    previous: "Précédent",
    next: "Suivant",
    page: "Page",
    of: "sur",
    "refresh-search": "Reactualiser la recherche",
  },
};
