name: Deploy Terraform and Upload to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ca-central-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        id: terraform
        working-directory: ./terraform
        run: terraform apply -var-file="main.tfvars" -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./client/arq-iac-client
        run: npm install

      - name: Build the app
        working-directory: ./client/arq-iac-client
        run: npm run build

      - name: Verify build directory
        run: ls ./client/arq-iac-client/

      - name: Extract S3 bucket name and cloudfront distribution
        working-directory: ./terraform
        run: |
          echo "S3_BUCKET_NAME=$(terraform output -raw website_bucket_name)" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV
          echo "API_BASE_URL=$(terraform output -raw base_url)" >> $GITHUB_ENV
          echo "IDENTITY_POOL_ID=$(terraform output -raw identity_pool_id)" >> $GITHUB_ENV
          echo "USER_POOL_CLIENT_ID=$(terraform output -raw user_pool_client_id)" >> $GITHUB_ENV
          echo "USER_POOL_ID=$(terraform output -raw user_pool_id)" >> $GITHUB_ENV

      - name: Compose .env file
        working-directory: ./client/arq-iac-client/dist
        run: |
          echo "VITE_BASE_URL=$API_BASE_URL" >> .env
          echo "VITE_IDENTITY_POOL_ID=$IDENTITY_POOL_ID" >> .env
          echo "VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID" >> .env
          echo "VITE_USER_POOL_ID=$USER_POOL_ID" >> .env

      - name: Sync content to S3
        working-directory: ./client/arq-iac-client/build
        run: aws s3 sync . s3://$S3_BUCKET_NAME --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"